shamefullyHoist: true

autoInstallPeers: true

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - nuxt
  - nuxt-nightly
  - '@nuxt/*'
  - vue
  - '@vue/*'
