name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
